#line 2 "lexer.cpp"

#line 4 "lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[265] =
    {   0,
        0,    0,    7,    7,    0,    0,    0,    0,    0,    0,
       71,   70,    3,   69,    5,    7,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   67,   67,   69,
       69,   69,   69,   68,   68,   68,   68,   68,   68,   69,
       69,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   69,    3,    4,
        2,    1,    4,    3,    7,   66,    0,   58,    0,    0,
       43,   49,   51,    0,   58,    0,   59,   46,   44,   45,
       57,   67,   60,   47,   67,   67,    0,    0,    0,   67,
        0,    0,    0,   67,    0,   61,   63,   65,   64,   62,

       50,   68,    0,    0,   68,   68,   68,   68,    6,    0,
       53,   68,   17,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   21,   68,   25,   36,   68,   68,
       33,   68,   68,   68,   68,   68,   68,   68,   52,    0,
        2,   58,    0,   58,   58,   56,   67,    0,   48,    0,
       67,    0,    0,   67,   67,    0,   67,    0,   67,   54,
       55,   68,   68,   68,   34,   68,   68,   68,   68,   68,
       68,   42,    9,   68,   68,   68,   68,   24,   68,   68,
       68,   68,   68,   32,   68,   68,   68,   27,   68,   68,
       68,    0,    0,    0,    0,    0,   58,    0,   67,    0,

       68,   40,   38,   68,   68,   68,   68,   68,   68,   22,
       23,   68,   68,   15,   68,   68,   68,   68,   10,   68,
       68,   68,   29,   68,    0,    0,    0,   58,   39,   68,
        8,   35,   11,   41,   68,   68,   68,   68,   68,   68,
       68,   14,   68,   26,   37,   58,    0,   58,   20,   68,
       30,   68,   18,   16,   31,   68,   13,   58,   68,   28,
       68,   12,   19,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    6,    1,    7,    8,    9,    1,
        1,   10,   11,    1,   12,   13,   14,   15,   16,   17,
       17,   17,   17,   17,   17,   18,   18,    1,    1,   19,
       20,   21,    1,   22,   23,   24,   23,   23,   25,   26,
       27,   27,   27,   28,   27,   27,   27,   29,   30,   27,
       27,   31,   27,   32,   33,   27,   27,   34,   27,   27,
       35,   36,   35,   37,   38,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   28,   48,   49,   50,   51,
       52,   53,   27,   54,   55,   56,   57,   27,   58,   59,
       60,   27,    1,   61,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    2,    1,    1,    3,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    4,    4,    4,    4,    1,    1,
        1,    1,    4,    4,    4,    4,    5,    5,    5,    5,
        5,    5,    5,    5,    1,    6,    1,    4,    4,    4,
        4,    4,    4,    4,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        1,    1
    } ;

static const flex_int16_t yy_base[276] =
    {   0,
      478,  477,    0,    0,   61,   63,  476,  475,  474,  473,
      534,  541,  541,  541,  541,  530,  512,   63,  529,  510,
      509,   61,   61,  508,   52,   62,   68,  113,   74,   64,
      507,   65,  506,    0,   88,  473,   95,  470,   96,   92,
      503,   52,  468,   57,  478,   59,  115,  471,  104,  480,
      466,  463,  477,  106,  461,   67,  467,  493,  541,  541,
      541,  541,  510,  541,  508,  541,  131,  505,  147,  507,
      541,  541,  541,  148,  155,  161,  488,  541,  541,  541,
      541,  160,  487,  541,  176,  192,  198,  164,  216,  541,
      222,  468,  227,  233,  237,  485,  541,  541,  541,  484,

      541,    0,  251,  250,  190,  454,  451,  444,  541,  131,
      541,  458,   80,  460,  455,  458,  445,  114,  126,  454,
      443,  414,  213,  415,    0,  403,    0,    0,  391,  133,
        0,  385,  392,  382,  377,  389,  379,  391,  541,  431,
      541,  541,  257,  259,  278,  541,  280,  284,  541,  294,
      209,  171,  299,  304,  309,  258,  394,  393,  318,  541,
      541,  375,  383,  382,    0,  381,  372,  375,  382,  364,
      362,    0,    0,  373,  371,  368,  371,    0,  358,  364,
      342,  352,  333,    0,  326,  311,  306,    0,  308,  309,
      304,  324,  325,  335,  349,  269,  362,  363,  362,  370,

      307,    0,    0,  295,  304,  285,  291,  273,  280,    0,
        0,  254,  257,    0,  264,  239,  248,  237,    0,  245,
      230,  238,    0,  237,  339,  360,  380,  394,    0,  213,
        0,    0,    0,    0,  216,  210,  208,  191,  173,  189,
      171,    0,  155,    0,    0,  378,  392,  407,    0,  143,
        0,  137,    0,    0,    0,  132,    0,  393,   79,    0,
       67,    0,    0,  541,  442,  448,  454,  459,  465,  467,
      472,   71,  478,  483,  488
    } ;

static const flex_int16_t yy_def[276] =
    {   0,
      265,  265,  264,    3,  266,  266,  265,  265,  265,  265,
      264,  264,  264,  264,  264,  264,  264,  267,  268,  264,
      264,  269,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  270,  270,  270,  270,  270,  270,  264,
      264,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  264,  264,  264,
      264,  264,  271,  264,  264,  264,  267,  264,  267,  268,
      264,  264,  264,  269,  269,  269,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  272,  264,  264,  264,  264,  264,  264,  264,  264,

      264,  270,  267,  269,  270,  270,  270,  270,  264,  264,
      264,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  264,  271,
      264,  264,  273,  269,  274,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  272,  272,  264,  264,
      264,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  273,  273,  273,  274,  275,  274,  274,  264,  264,

      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  273,  275,  275,  274,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  273,  275,  274,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  275,  270,  270,
      270,  270,  270,    0,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264
    } ;

static const flex_int16_t yy_nxt[604] =
    {   0,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   29,   29,   30,   31,
       32,   33,   34,   34,   34,   35,   34,   34,   36,   34,
       37,   38,   39,   34,   14,   40,   41,   34,   42,   43,
       44,   45,   46,   47,   48,   34,   49,   34,   50,   34,
       51,   52,   53,   54,   34,   55,   39,   56,   34,   57,
       58,   59,   61,   62,   61,   62,   63,   68,   63,   75,
       77,   80,   81,   76,  157,   69,   82,   82,   82,   82,
       78,   83,   96,   97,   99,  100,   85,   84,   94,   94,
       94,   94,  103,  109,  110,   76,  104,   69,   89,  103,

      103,   90,  112,  104,  104,  116,  113,  119,  117,  114,
      103,   95,  136,  137,  104,  263,   89,  120,  105,  103,
      105,  262,   64,  104,   64,   85,  106,   86,   87,   87,
       87,  105,  109,  110,  166,  142,   88,   89,  105,  167,
       90,  105,   91,   69,  133,  105,   92,  125,  134,  105,
       93,  142,   88,  126,  127,   89,  144,  172,  128,   69,
       76,  121,  173,  145,   91,   69,  122,   76,  123,  144,
      261,   92,  174,   76,  147,  147,  147,  147,  151,  151,
      175,   69,   76,  183,   89,  151,  151,   90,  184,   76,
       82,   82,   82,   82,  103,   76,  260,  148,  104,  259,

       89,  152,   89,   90,   85,  257,   86,   87,   87,   87,
       85,  256,   87,   87,   87,   87,   89,  103,   89,   90,
      153,  104,   89,  151,  151,   90,  153,  255,  254,   93,
      154,  154,  154,  154,   89,  150,  155,  155,  155,  253,
       89,  159,   87,   87,   87,   85,  152,   94,   94,   94,
       94,   94,   94,   94,   94,   68,  252,   89,   75,  156,
       90,  193,   76,   69,  179,  251,  250,  144,  249,  194,
       95,   76,  155,  155,  155,   89,  153,  226,  245,  196,
      244,  227,  196,  243,   76,   69,  197,  242,  241,  240,
      198,  194,  239,   76,  147,  147,  147,  147,  147,  147,

      147,  147,  238,  227,   89,  237,  236,   90,   87,   87,
       87,   87,  198,  154,  154,  154,  154,  148,  199,  199,
      199,  199,   89,  155,  155,  155,  235,  234,  193,  225,
       85,   90,  159,   87,   87,   87,  194,  194,  233,  193,
      232,  200,   89,  246,  231,   90,  156,  194,  230,  229,
      196,  194,  224,  196,  223,   93,  222,  197,  194,  194,
       89,  198,  221,  196,  196,  220,  196,  196,  247,  194,
      228,  197,  227,  194,  198,  198,  199,  199,  199,  199,
      219,  218,  246,  198,  199,  199,  199,  199,  226,   90,
      194,  217,  227,  216,  227,  196,  198,  198,  196,  200,

      258,  258,  248,  215,  227,  227,  198,  214,  196,  213,
      212,  196,  194,  211,  227,  248,  210,  209,  208,  198,
      207,  206,  205,  204,  203,  202,  227,  227,  198,  201,
      264,  158,  141,  191,  190,  189,  188,  187,  186,  185,
      182,  198,   12,   12,   12,   12,   12,   12,   60,   60,
       60,   60,   60,   60,   67,  181,   67,   67,   67,   70,
       70,   70,   70,   70,   70,   74,  180,  178,   74,   74,
      102,  102,  140,  140,  140,  140,  140,  140,  192,  192,
      192,  192,  192,  195,  195,  195,  195,  195,  196,  196,
      196,  196,  196,  177,  176,  171,  170,  169,  168,  165,

      164,  163,  162,  161,  160,  158,  149,  146,   71,  143,
       65,  141,  139,  138,  135,  132,  131,  130,  129,  124,
      118,  115,  111,  108,  107,  101,   98,   79,   73,   72,
       71,   66,   65,  264,   13,   13,   13,   13,   13,   13,
       11,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,

      264,  264,  264
    } ;

static const flex_int16_t yy_chk[604] =
    {   0,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    5,    5,    6,    6,    5,   18,    6,   22,
       23,   25,   25,   22,  272,   18,   26,   26,   26,   26,
       23,   27,   30,   30,   32,   32,   29,   27,   29,   29,
       29,   29,   35,   40,   40,   22,   35,   18,   29,   37,

       39,   29,   42,   37,   39,   44,   42,   46,   44,   42,
       54,   29,   56,   56,   54,  261,   29,   46,   35,   47,
       37,  259,    5,   47,    6,   28,   35,   28,   28,   28,
       28,   54,  110,  110,  113,   67,   28,   28,   37,  113,
       28,   35,   28,   67,   54,   47,   28,   49,   54,   54,
       28,   69,   28,   49,   49,   28,   74,  118,   49,   69,
       74,   47,  118,   75,   28,   67,   47,   75,   47,   76,
      256,   28,  119,   76,   82,   82,   82,   82,   88,   88,
      119,   69,   74,  130,   82,  152,  152,   82,  130,   75,
       85,   85,   85,   85,  105,   76,  252,   82,  105,  250,

       85,   88,   82,   85,   86,  243,   86,   86,   86,   86,
       87,  241,   87,   87,   87,   87,   86,  123,   85,   86,
       89,  123,   87,  151,  151,   87,   89,  240,  239,   86,
       89,   89,   89,   89,   86,   87,   91,   91,   91,  238,
       87,   93,   93,   93,   93,   94,  151,   94,   94,   94,
       94,   95,   95,   95,   95,  103,  237,   94,  104,   91,
       94,  143,  104,  103,  123,  236,  235,  144,  230,  143,
       94,  144,  156,  156,  156,   94,   89,  196,  224,  145,
      222,  196,  145,  221,  104,  103,  145,  220,  218,  217,
      145,  143,  216,  144,  147,  147,  147,  147,  148,  148,

      148,  148,  215,  196,  147,  213,  212,  147,  150,  150,
      150,  150,  145,  153,  153,  153,  153,  147,  154,  154,
      154,  154,  147,  155,  155,  155,  209,  208,  192,  193,
      159,  154,  159,  159,  159,  159,  192,  193,  207,  194,
      206,  154,  159,  225,  205,  159,  155,  194,  204,  201,
      195,  225,  191,  195,  190,  159,  189,  195,  192,  193,
      159,  195,  187,  197,  198,  186,  197,  198,  226,  194,
      197,  198,  226,  225,  197,  198,  199,  199,  199,  199,
      185,  183,  246,  195,  200,  200,  200,  200,  227,  199,
      246,  182,  227,  181,  226,  228,  197,  198,  228,  199,

      247,  258,  228,  180,  247,  258,  228,  179,  248,  177,
      176,  248,  246,  175,  227,  248,  174,  171,  170,  248,
      169,  168,  167,  166,  164,  163,  247,  258,  228,  162,
      158,  157,  140,  138,  137,  136,  135,  134,  133,  132,
      129,  248,  265,  265,  265,  265,  265,  265,  266,  266,
      266,  266,  266,  266,  267,  126,  267,  267,  267,  268,
      268,  268,  268,  268,  268,  269,  124,  122,  269,  269,
      270,  270,  271,  271,  271,  271,  271,  271,  273,  273,
      273,  273,  273,  274,  274,  274,  274,  274,  275,  275,
      275,  275,  275,  121,  120,  117,  116,  115,  114,  112,

      108,  107,  106,  100,   96,   92,   83,   77,   70,   68,
       65,   63,   58,   57,   55,   53,   52,   51,   50,   48,
       45,   43,   41,   38,   36,   33,   31,   24,   21,   20,
       19,   17,   16,   11,   10,    9,    8,    7,    2,    1,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,

      264,  264,  264
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[71] =
    {   0,
0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 4 "lexer.l"
#include<bits/stdc++.h>
#include "parser.tab.hpp"
// #include "node.hpp"
using std::stack;
stack<int> indents;
int indent = 0;
int space = 0;
bool spaceset = false;
int inside_line = 0;
int sq_pos = 0;
int cu_pos = 0;
int br_pos = 0;
// int setspace()
// {
//     spaceset = true;
//     if(indent > indents.top()){ 
//     indents.push(indent); 
//     printf("INDENT\n");
//     return 1;
//     } 
//     int ctr = 0; 
//     while(indent < indents.top()){ 
//     ctr++; 
//     indents.pop(); 
//     } 
//     if(indents.top() != indent){ 
//     printf("Indentation error\n"); 
//     return 0;
//     } 
//     dedpos = ctr; 
//     return 0;
// }
#line 729 "lexer.cpp"

#line 731 "lexer.cpp"

#define INITIAL 0
#define INLINE 1
#define OUTLINE 2
#define ARRAY 3
#define BRACKET 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 108 "lexer.l"


#line 111 "lexer.l"
    if(inside_line) BEGIN(INLINE);
    else BEGIN(OUTLINE);
#line 958 "lexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 265 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 541 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 113 "lexer.l"
{space++; /*cerr<<"uninline space detected\n";*/}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 116 "lexer.l"
{
    cerr << "Empty line\n";
    space = 0;
    inside_line = 0;
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(INLINE):
case YY_STATE_EOF(OUTLINE):
case YY_STATE_EOF(ARRAY):
case YY_STATE_EOF(BRACKET):
#line 121 "lexer.l"
{
    if(indents.size() > 1){
        indents.pop();
        yylval.val = "DEDENT";
        yylval.ptr = new node("DEDENT", "DEDENT");
        unput(yytext[0]);
        return DEDENT;
    }
    cerr << "returning end\n";
    yylval.val = "ENDMARKER";
    yylval.ptr = new node("ENDMARKER", yylval.val);
    return ENDMARKER;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 134 "lexer.l"
{
    if(indents.size() > 1){
        indents.pop();
        yylval.val = "DEDENT";
        yylval.ptr = new node("DEDENT", "DEDENT");
        unput(yytext[0]);
        return DEDENT;
    }
    cerr << "returning end\n";
    yylval.val = "ENDMARKER";
    yylval.ptr = new node("ENDMARKER", yylval.val);
    return ENDMARKER;   
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 147 "lexer.l"
{
        cerr << "here ex\n";
        int pos = space;
        cerr << "pos: " << pos << ' ' << int(yytext[0]) << ' ' << yyleng << '\n';
        if(pos > indents.top()){
            inside_line = true;
            unput(yytext[0]);
            indents.push(pos);
            yylval.val = "INDENT";
            yylval.ptr = new node(yylval.val, yylval.val);
            cerr << "return indent\n";
            return INDENT;
        }
        else if(pos == indents.top()){
            inside_line = true;
            BEGIN(INLINE);
            unput(yytext[0]);
        }
        else if(pos < indents.top()){
            indents.pop();
            unput(yytext[0]);
            yylval.val = "DEDENT";
            yylval.ptr = new node(yylval.val, yylval.val);
            cerr<<"\n\nreturning dedent\n\n";
            return DEDENT;
        }
    }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 176 "lexer.l"
{
    yylval.ptr = new node("NEWLINE", "NEWLINE");
    yylval.val = "NEWLINE";
    inside_line = 0;
    space = 0;
    // cerr << "return newline token";
    return NEWLINE;
}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 185 "lexer.l"
{
    cerr << "line joining\n";
} 
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 189 "lexer.l"
{/*cerr << "space\n";*/}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 192 "lexer.l"
{ 
    yylval.ptr = new node("KEYWORD", "async");
    yylval.val = "async";
    return ASYNC;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 196 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "del");
    yylval.val = "del";
    return DEL;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 200 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "pass");
    yylval.val = "pass";
    return PASS;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 204 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "break");
    yylval.val = "break";
    return BREAK;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 208 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "continue");
    yylval.val = "continue";
    return CONTINUE;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 212 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "return");
    yylval.val = "return";
    return RETURN;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 216 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "raise");
    yylval.val = "raise";
    return RAISE;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 220 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "from");
    yylval.val = "from";
    return FROM;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 224 "lexer.l"
{
    // cerr<<"import detected\n";
    yylval.ptr = new node("KEYWORD", "import");
    yylval.val = "import";
    return IMPORT;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 229 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "as");
    yylval.val = "as";
    return AS;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 233 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "global");
    yylval.val = "global";
    return GLOBAL;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 237 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "nonlocal");
    yylval.val = "nonlocal";
    return NONLOCAL;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 241 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "assert");
    yylval.val = "assert";
    return ASSERT;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 245 "lexer.l"
{
    cerr<<"if read\n";
    yylval.ptr = new node("KEYWORD", "if");
    yylval.val = "if";
    return IF;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 250 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "elif");
    yylval.val = "elif";
    return ELIF;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 254 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "else");
    yylval.val = "else";
    return ELSE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 258 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "for");
    yylval.val = "for";
    return FOR;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 262 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "in");
    yylval.val = "in";
    return IN;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 266 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "while");
    yylval.val = "while";
    return WHILE;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 270 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "try");
    yylval.val = "try";
    return TRY;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 274 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "finally");
    yylval.val = "finally";
    return FINALLY;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 278 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "with");
    yylval.val = "with";
    return WITH;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 282 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "except");
    yylval.val = "except";
    return EXCEPT;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 286 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "lambda");
    yylval.val = "lambda";
    return LAMBDA;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 290 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "not");
    yylval.val = "not";
    return NOT;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 294 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "or");
    yylval.val = "or";
    return OR;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 298 "lexer.l"
{
    cerr << "returning end\n";
    yylval.ptr = new node("KEYWORD", "and");
    yylval.val = "and";
    return AND;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 303 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "await");
    yylval.val = "await";
    return AWAIT;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 307 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "is");
    yylval.val = "is";
    return IS;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 311 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "yield");
    yylval.val = "yield";
    return YIELD;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 315 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "True");
    yylval.val = "True";
    return TRUE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 319 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "False");
    yylval.val = "False";
    return FALSE;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 323 "lexer.l"
{
    cerr << "return keyword none\n";
    yylval.ptr = new node("KEYWORD", "None");
    yylval.val = "None";
    return NONE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 328 "lexer.l"
{
    yylval.ptr = new node("KEYWORD", "class");
    yylval.val = "class";
    return CLASS;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 332 "lexer.l"
{
    cerr << "returning def\n";
    yylval.ptr = new node("KEYWORD", "def");
    yylval.val = "def";
    return DEF;}
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 338 "lexer.l"
{
    yylval.ptr = new node("NEWLINE", "NEWLINE");
    yylval.val = "NEWLINE";
    inside_line = 0;
    space = 0;
    // cerr << "return newline token";
    return NEWLINE;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 346 "lexer.l"
{
    yylval.ptr = new node("OPERATOR", "+=");
    yylval.val = "+=";
    return ADDASSIGN;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 350 "lexer.l"
{
    yylval.ptr = new node("OPERATOR", "-=");
    yylval.val = "-=";
    return SUBASSIGN;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 354 "lexer.l"
{
    yylval.ptr = new node("OPERATOR", "*=");
    yylval.val = "*=";
    return MULASSIGN;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 358 "lexer.l"
{
    yylval.ptr = new node("OPERATOR", "/=");
    yylval.val = "/=";
    return DIVASSIGN;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 362 "lexer.l"
{
    yylval.ptr = new node("OPERATOR", "//=");
    yylval.val = "//=";
    return IDIVASSIGN;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 366 "lexer.l"
{
    yylval.ptr = new node("OPERATOR", "%=");
    yylval.val = "%=";
    return MODASSIGN;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 370 "lexer.l"
{
    yylval.ptr = new node("OPERATOR", "@=");
    yylval.val = "@=";
    return ATASSIGN;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 374 "lexer.l"
{
    yylval.ptr = new node("OPERATOR", "&=");
    yylval.val = "&=";
    return ANDASSIGN;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 378 "lexer.l"
{
    yylval.ptr = new node("OPERATOR", "|=");
    yylval.val = "|=";
    return ORASSIGN;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 382 "lexer.l"
{
    yylval.ptr = new node("OPERATOR", "^=");
    yylval.val = "^=";
    return XORASSIGN;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 386 "lexer.l"
{
    yylval.ptr = new node("OPERATOR", "<<=");
    yylval.val = "<<=";
    return LSASSIGN;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 390 "lexer.l"
{
    yylval.ptr = new node("OPERATOR", ">>=");
    yylval.val = ">>=";
    return RSASSIGN;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 394 "lexer.l"
{
    yylval.ptr = new node("OPERATOR", "**=");
    yylval.val = "**=";
    return POWASSIGN;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 398 "lexer.l"
{
    cerr << "returing arrow OP\n";
    yylval.ptr = new node("OPERATOR", "->");
    yylval.val = "->";
    return ARROWOP;}
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 404 "lexer.l"
{ 
    yylval.ptr = new node("STRING LITERAL", string(yytext, yytext + yyleng));
    yylval.val = string(yytext, yytext + yyleng);
    return STRING;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 408 "lexer.l"
{
    yylval.ptr = new node("OPERATOR", "**");
    yylval.val = "**";
    return POW;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 412 "lexer.l"
{
    yylval.ptr = new node("OPERATOR", "//");
    yylval.val = "//";
    return IDIV;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 416 "lexer.l"
{
    yylval.ptr = new node("OPERATOR", "<<");
    yylval.val = "<<";
    return LEFTSHIFT;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 420 "lexer.l"
{
    yylval.ptr = new node("OPERATOR", ">>");
    yylval.val = ">>";
    return RIGHTSHIFT;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 424 "lexer.l"
{
    yylval.ptr = new node("OPERATOR", "<=");
    yylval.val = "<=";
    return LEQ;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 428 "lexer.l"
{
    yylval.ptr = new node("OPERATOR", ">=");
    yylval.val = ">=";
    return GEQ;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 432 "lexer.l"
{
    yylval.ptr = new node("OPERATOR", "==");
    yylval.val = "==";
    return EQUAL;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 436 "lexer.l"
{
    yylval.ptr = new node("OPERATOR", "!=");
    yylval.val = "!=";
    return NEQ;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 440 "lexer.l"
{
    cerr << "here number "<< yytext <<"\n";
    yylval.val = string(yytext, yytext + yyleng);
    yylval.ptr = new node("NUMBER", yylval.val);
    return NUMBER;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 445 "lexer.l"
{
    cerr << "here name "<<yytext<<"\n";
    yylval.val = string(yytext, yytext + yyleng);
    yylval.ptr = new node("IDENTIFIER", yylval.val);
    return NAME;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 450 "lexer.l"
{
    cerr << "here delimiter "<<yytext<<"\n";
    yylval.val = string(1, yytext[0]);
    yylval.ptr = new node("DELIMITER", yylval.val);
    return yytext[0];}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 457 "lexer.l"
ECHO;
	YY_BREAK
#line 1650 "lexer.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 62);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 265 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 62;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 265 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 264);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 457 "lexer.l"


