#line 2 "modif.cpp"

#line 4 "modif.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[428] =
    {   0,
        0,    0,   66,   63,   37,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   61,   63,   63,   63,   63,
       62,   62,   62,   63,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   63,   63,   63,    1,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   61,   63,   63,   63,
       63,   62,   62,   62,   63,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   63,   63,   60,    0,   38,   44,   46,   53,
       41,   39,   40,   52,   61,   54,   42,   61,    0,    0,

        0,   61,    0,    0,    0,   61,   61,    0,   55,   57,
       59,   58,   56,   45,   62,   62,   62,   48,    0,   62,
       11,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   15,   62,   19,   30,   62,   62,   27,   62,
       62,   62,   62,   62,   62,   62,   62,   47,   64,    1,
        0,   60,   64,   44,   46,   53,   41,   39,   40,   52,
       61,   54,   42,   61,   64,   64,   64,   61,   64,   64,
       64,   61,   61,   64,   55,   57,   59,   58,   56,   45,
       62,   62,   62,   48,   64,   62,   11,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   15,   62,

       19,   30,   62,   62,   27,   62,   62,   62,   62,   62,
       62,   62,   62,   47,   51,   61,    0,   43,   61,    0,
        0,   61,   61,    0,   61,    0,   61,    0,   49,   50,
       62,   62,   28,   62,   62,   62,   62,   62,   62,   36,
        3,   62,   62,   62,   62,   18,   62,   62,   62,   62,
       62,   26,   62,   62,   62,   62,   21,   62,   62,   62,
       51,   61,   64,   43,   61,   64,   64,   61,   61,   64,
       61,   64,   61,   64,   49,   50,   62,   62,   28,   62,
       62,   62,   62,   62,   62,   36,    3,   62,   62,   62,
       62,   18,   62,   62,   62,   62,   62,   26,   62,   62,

       62,   62,   21,   62,   62,   62,   61,    0,   61,   62,
       34,   62,   62,   62,   62,   62,   62,   16,   17,   62,
       62,    9,   62,   62,   62,   62,    4,   62,   62,   62,
       62,   23,   62,   61,   64,   61,   62,   34,   62,   62,
       62,   62,   62,   62,   16,   17,   62,   62,    9,   62,
       62,   62,   62,    4,   62,   62,   62,   62,   23,   62,
       33,   62,    2,   29,    5,   35,   62,   62,   62,   62,
       62,   62,   62,    8,   62,   62,   20,   31,   33,   62,
        2,   29,    5,   35,   62,   62,   62,   62,   62,   62,
       62,    8,   62,   62,   20,   31,   14,   62,   24,   62,

       12,   10,   25,   62,    7,   32,   14,   62,   24,   62,
       12,   10,   25,   62,    7,   32,   62,   22,   62,   62,
       22,   62,    6,   13,    6,   13,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    6,    1,    7,    8,    1,    1,
        1,    9,   10,    1,   11,   12,   13,   14,   15,   16,
       16,   16,   16,   16,   16,   17,   17,    1,    1,   18,
       19,   20,    1,   21,   22,   23,   22,   22,   24,   25,
       26,   26,   26,   27,   26,   26,   26,   28,   29,   26,
       26,   26,   26,   26,   26,   26,   26,   30,   26,   26,
        1,    1,    1,   31,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   27,   42,   43,   44,   45,
       46,   47,   26,   48,   49,   50,   51,   26,   52,   53,
       54,   26,   55,   56,   55,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[57] =
    {   0,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    1,    1,    1,
        1,    3,    3,    3,    3,    4,    4,    4,    4,    4,
        1,    3,    3,    3,    3,    3,    3,    3,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1
    } ;

static const flex_int16_t yy_base[434] =
    {   0,
        0,   56,  896,  897,  897,  876,  892,  874,  873,  104,
      872,   95,  102,  107,  115,  157,  103,  871,  105,  870,
        0,  855,  841,  867,  131,  837,   90,  116,   97,  100,
      122,  147,  851,  837,  834,  123,  125,  831,  139,  114,
      839,  867,  859,    0,  897,  161,  858,  164,  857,  856,
      151,  855,  158,  183,  169,  189,  231,  189,  854,  190,
      853,  268,  324,  169,  852,  205,  142,  181,  199,  187,
      218,  219,  258,  837,  195,  189,  227,  271,  211,  272,
      252,  192,  857,  849,  897,  865,  897,  897,  897,  847,
      897,  897,  897,  897,  324,  846,  897,  273,  369,  280,

      348,  897,  355,  832,  299,  235,  849,  358,  843,  897,
      897,  897,  842,  897,    0,  817,  814,  897,  374,  822,
      180,  824,  819,  822,  809,  263,  241,  818,  807,  803,
      804,  803,    0,  801,    0,    0,  803,  272,    0,  797,
      804,  794,  795,  788,  800,  790,  802,  897,    0,  897,
      316,    0,  324,    0,    0,  819,    0,    0,    0,    0,
      383,  818,    0,  322,  379,  362,  407,    0,  412,  450,
      419,  477,  503,  423,  817,    0,    0,    0,  816,    0,
      801,  278,  220,    0,  431,  314,  362,  800,  345,  799,
      321,  416,  319,  160,  385,  223,  359,  396,  798,  408,

      797,  796,  265,  445,  795,  370,  410,  381,  420,  417,
      419,  429,  424,    0,  897,  507,  482,  897,  493,  455,
      496,  531,  522,  527,  795,  794,    0,  535,  897,  897,
      776,  787,    0,  786,  777,  780,  787,  770,  768,    0,
        0,  779,  779,  778,  781,    0,  769,  778,  765,  776,
      766,    0,  759,  758,  755,  764,    0,  761,  763,  759,
        0,  545,  550,    0,  541,  462,  564,  569,  560,  573,
        0,  769,  590,  583,    0,    0,  467,  469,  767,  495,
      558,  575,  766,  560,  520,  765,  764,  557,  496,  578,
      763,  762,  524,  447,  577,  579,  585,  761,  586,  587,

      588,  591,  760,  597,  146,  598,  628,  632,  778,  754,
        0,  742,  754,  738,  745,  737,  744,    0,    0,  737,
      740,    0,  749,  733,  744,  733,    0,  741,  729,  731,
      738,    0,  738,  636,  642,  657,  592,  740,  628,  423,
      604,  633,  629,  593,  739,  738,  632,  634,  737,  736,
      637,  647,  649,  735,  653,  654,  655,  659,  734,  665,
        0,  716,    0,    0,    0,    0,  720,  714,  720,  719,
      711,  727,  724,    0,  713,  718,    0,    0,  723,  658,
      722,  721,  720,  719,  660,  664,  666,  670,  671,  718,
      470,  715,  673,  677,  707,  698,    0,  679,    0,  675,

        0,    0,    0,  695,    0,    0,  694,  674,  693,  678,
      691,  690,  687,  684,  631,  605,  596,    0,  551,  682,
      538,  679,    0,    0,  493,  334,  897,  732,  734,  738,
      742,  746,  154
    } ;

static const flex_int16_t yy_def[434] =
    {   0,
      427,  427,  427,  427,  427,  427,  428,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      429,  429,  429,  427,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  427,  427,  430,  427,  430,  430,  431,  430,  430,
      430,  430,  430,  430,  430,  430,  430,  430,  430,  430,
      430,  432,  432,   63,  430,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,  430,  430,  427,  428,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,

      427,  427,  427,  433,  427,   16,   16,  427,  427,  427,
      427,  427,  427,  427,  429,  429,  429,  427,  427,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  427,  430,  427,
      430,  430,  431,  430,  430,  430,  430,  430,  430,  430,
      430,  430,  430,  430,   56,  430,  430,  430,  430,  430,
      430,  430,  430,  430,  430,  430,  430,  430,  430,  430,
       63,   63,   63,  430,  430,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,

       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,  430,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  433,  433,  106,  427,  427,  427,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      430,  430,  430,  430,  430,  430,  430,  430,  430,  430,
      170,  170,  430,  430,  430,  430,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,

       63,   63,   63,   63,   63,   63,  427,  427,  106,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  430,  430,  430,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,  429,  429,  429,  429,

      429,  429,  429,  429,  429,  429,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,  429,  429,  429,   63,
       63,   63,  429,  429,   63,   63,    0,  427,  427,  427,
      427,  427,  427
    } ;

static const flex_int16_t yy_nxt[954] =
    {   0,
        4,    5,    4,    6,    4,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   16,   16,   17,   18,   19,
       20,   21,   21,   21,   22,   21,   21,   23,   21,   21,
       24,   21,   25,   26,   27,   28,   29,   30,   31,   21,
       32,   21,   33,   21,   34,   35,   36,   37,   38,   39,
       21,   40,   21,   41,   42,   43,   44,   45,   46,   47,
       44,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       57,   57,   57,   58,   59,   60,   61,   62,   62,   62,
       63,   62,   62,   64,   62,   62,   65,   62,   66,   67,
       68,   69,   70,   71,   72,   62,   73,   62,   74,   62,

       75,   76,   77,   78,   79,   80,   62,   81,   62,   82,
       83,   84,   90,   93,   94,   95,   95,   95,   95,   96,
      109,  110,   91,  112,  113,   97,   98,  119,   99,   99,
       99,   99,  124,  119,  119,  125,  119,  100,  101,  127,
      129,  102,  119,  103,  104,  130,  105,  131,  100,  128,
      119,  101,  126,  145,  146,  140,  225,  141,  119,  156,
      103,  142,  150,  151,  132,   87,   86,  104,   98,  157,
      106,  107,  107,  107,  181,  120,  159,  160,  181,  121,
      101,  162,  122,  102,  133,  359,  144,  163,  108,  189,
      134,  135,  181,  101,  290,  136,  161,  161,  161,  161,

      164,  181,  165,  165,  165,  165,  175,  176,  178,  179,
      185,  166,  167,  181,  183,  168,  185,  169,  170,  181,
      171,  181,  166,  190,  181,  167,  191,  181,  234,  193,
      185,  181,  213,  235,  169,  192,  205,  181,  185,  194,
      204,  170,  164,  181,  172,  173,  173,  173,  227,  186,
      181,  181,  181,  187,  167,  181,  188,  168,  195,  206,
      209,  198,  174,  196,  278,  197,  228,  167,  149,  185,
      292,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  242,  185,  185,  181,  149,  149,  149,  149,  243,
      181,  211,  212,  219,  219,  199,  101,  181,  149,  102,

      240,  200,  201,  207,  181,  241,  202,  208,  296,  101,
      181,  220,   99,   99,   99,   99,  251,  150,  151,  210,
      277,  252,  149,  149,  149,   87,   86,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  216,  216,  216,
      216,  149,  149,  149,  149,  167,  181,  101,  168,  279,
      102,  181,  221,  181,  149,  217,  182,  221,  167,  288,
      101,  222,  222,  222,  222,  285,  181,  289,  223,  223,
      223,  107,  107,  107,  107,  265,  265,  181,  149,  149,
       98,  283,   99,   99,   99,   99,  224,   95,   95,   95,
       95,  181,  101,  266,  181,  102,  262,  262,  262,  262,

      105,  149,  181,  221,  293,  101,  167,  149,  149,  168,
      280,  267,  149,  181,  263,  281,  267,  181,  299,  167,
      268,  268,  268,  268,  149,  269,  269,  269,  181,  291,
      301,  149,  165,  165,  165,  165,  173,  173,  173,  173,
      181,  294,  181,  270,  161,  161,  161,  161,  181,  181,
      300,  181,  181,  286,  295,  181,  181,  381,  287,  304,
      306,  181,  267,  271,  271,  271,  271,  302,  219,  219,
      303,  271,  271,  271,  271,  265,  265,  181,  305,  181,
      350,  272,  271,  271,  271,  271,  271,  271,  164,  297,
      273,  173,  173,  173,  298,  216,  216,  216,  216,  181,

      167,  181,  181,  168,  414,  338,  219,  219,  274,  222,
      222,  222,  222,  167,  164,  337,  173,  173,  173,  173,
      216,  216,  216,  216,  220,  181,  167,  181,  181,  168,
      101,  339,  346,  102,  174,  223,  223,  223,  217,  167,
      223,  223,  223,  101,  307,  307,  307,  307,  309,  107,
      107,  107,  181,  224,  265,  265,  181,  102,  262,  262,
      262,  262,  308,  262,  262,  262,  262,  349,  167,  344,
      181,  168,  266,  269,  269,  269,  263,  268,  268,  268,
      268,  167,  334,  334,  334,  334,  269,  269,  269,  181,
      181,  270,  181,  424,  345,  168,  336,  173,  173,  173,

      335,  164,  340,  273,  173,  173,  173,  181,  343,  181,
      181,  181,  352,  167,  347,  341,  168,  181,  181,  181,
      181,  274,  351,  181,  181,  181,  167,  353,  379,  181,
      181,  357,  423,  385,  354,  355,  181,  181,  356,  358,
      360,  307,  307,  307,  307,  307,  307,  307,  307,  334,
      334,  334,  334,  382,  102,  334,  334,  334,  334,  308,
      181,  181,  168,  181,  181,  181,  181,  335,  164,  181,
      336,  173,  173,  173,  383,  380,  387,  384,  386,  181,
      167,  181,  390,  168,  389,  181,  181,  181,  274,  392,
      181,  181,  181,  167,  391,  395,  181,  181,  181,  394,

      396,  393,  181,  181,  408,  181,  181,  407,  410,  181,
      181,  181,  411,  409,  181,  416,  422,  415,  425,  181,
      412,  426,  181,  181,  420,  181,  181,  419,  418,  417,
      181,  421,   86,   86,   86,   86,  115,  115,  149,  181,
      149,  149,  153,  153,  153,  153,  181,  181,  181,  181,
      413,  181,  181,  181,  181,  181,  406,  405,  404,  403,
      402,  401,  400,  399,  398,  397,  181,  181,  388,  181,
      181,  181,  181,  378,  377,  376,  375,  374,  373,  372,
      371,  370,  369,  368,  367,  366,  365,  364,  363,  362,
      361,  309,  181,  181,  181,  348,  181,  181,  342,  181,

      149,  333,  332,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  320,  319,  318,  317,  316,  315,
      314,  313,  312,  311,  310,  427,  226,  181,  181,  181,
      181,  284,  282,  181,  276,  275,  264,  261,  260,  259,
      258,  257,  256,  255,  254,  253,  250,  249,  248,  247,
      246,  245,  244,  239,  238,  237,  236,  233,  232,  231,
      230,  229,  107,  226,  218,  215,   87,  214,  185,  203,
      184,  180,  177,  158,  155,  154,  152,  148,  119,  147,
      143,  139,  138,  137,  123,  118,  117,  116,  114,  111,
       92,   89,   88,   87,   85,  427,    3,  427,  427,  427,

      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427
    } ;

static const flex_int16_t yy_chk[954] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,   10,   12,   12,   13,   13,   13,   13,   14,
       17,   17,   10,   19,   19,   14,   15,   28,   15,   15,
       15,   15,   27,   31,   36,   27,   37,   15,   15,   29,
       30,   15,   25,   15,   15,   30,   15,   30,   15,   29,
       39,   15,   28,   40,   40,   36,  433,   37,   32,   51,
       15,   37,   46,   46,   31,   48,   48,   15,   16,   51,
       16,   16,   16,   16,   67,   25,   53,   53,  305,   25,
       16,   55,   25,   16,   32,  305,   39,   55,   16,   67,
       32,   32,  194,   16,  194,   32,   54,   54,   54,   54,

       56,   64,   56,   56,   56,   56,   58,   58,   60,   60,
       69,   56,   56,   68,   64,   56,   66,   56,   56,   70,
       56,   76,   56,   68,   82,   56,   68,   75,  121,   70,
       72,   69,   82,  121,   56,   69,   76,   66,   77,   70,
       75,   56,   57,   79,   57,   57,   57,   57,  106,   66,
       71,   72,  183,   66,   57,  196,   66,   57,   71,   77,
       79,   72,   57,   71,  183,   71,  106,   57,   62,   73,
      196,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,  127,   78,   80,   81,   62,   62,   62,   62,  127,
       73,   81,   81,  100,  100,   73,   98,  203,   62,   98,

      126,   73,   73,   78,   80,  126,   73,   78,  203,   98,
      182,  100,  105,  105,  105,  105,  138,  151,  151,   80,
      182,  138,   62,   62,   63,  153,  153,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   95,   95,   95,
       95,   63,   63,   63,   63,  164,  186,   95,  164,  186,
       95,  193,  101,  191,   63,   95,   63,  101,  164,  193,
       95,  101,  101,  101,  101,  191,  426,  193,  103,  103,
      103,  108,  108,  108,  108,  166,  166,  189,   63,   63,
       99,  189,   99,   99,   99,   99,  103,  119,  119,  119,
      119,  197,   99,  166,  187,   99,  161,  161,  161,  161,

       99,  165,  206,  101,  197,   99,  161,  165,  165,  161,
      187,  167,  165,  208,  161,  187,  167,  195,  206,  161,
      167,  167,  167,  167,  165,  169,  169,  169,  198,  195,
      208,  165,  171,  171,  171,  171,  174,  174,  174,  174,
      200,  198,  207,  169,  185,  185,  185,  185,  192,  210,
      207,  211,  209,  192,  200,  340,  213,  340,  192,  211,
      213,  212,  167,  170,  170,  170,  170,  209,  220,  220,
      210,  170,  170,  170,  170,  266,  266,  204,  212,  294,
      294,  170,  170,  170,  170,  170,  170,  170,  172,  204,
      172,  172,  172,  172,  204,  217,  217,  217,  217,  277,

      172,  278,  391,  172,  391,  278,  219,  219,  172,  221,
      221,  221,  221,  172,  173,  277,  173,  173,  173,  173,
      216,  216,  216,  216,  219,  425,  173,  280,  289,  173,
      216,  280,  289,  216,  173,  223,  223,  223,  216,  173,
      224,  224,  224,  216,  222,  222,  222,  222,  228,  228,
      228,  228,  285,  223,  265,  265,  293,  222,  262,  262,
      262,  262,  222,  263,  263,  263,  263,  293,  262,  285,
      421,  262,  265,  269,  269,  269,  262,  267,  267,  267,
      267,  262,  268,  268,  268,  268,  270,  270,  270,  288,
      281,  269,  284,  419,  288,  268,  274,  274,  274,  274,

      268,  273,  281,  273,  273,  273,  273,  282,  284,  295,
      290,  296,  296,  273,  290,  282,  273,  297,  299,  300,
      301,  273,  295,  302,  337,  344,  273,  297,  337,  304,
      306,  302,  417,  344,  299,  300,  341,  416,  301,  304,
      306,  307,  307,  307,  307,  308,  308,  308,  308,  334,
      334,  334,  334,  341,  307,  335,  335,  335,  335,  307,
      339,  343,  334,  415,  347,  342,  348,  334,  336,  351,
      336,  336,  336,  336,  342,  339,  348,  343,  347,  352,
      336,  353,  352,  336,  351,  355,  356,  357,  336,  355,
      380,  358,  385,  336,  353,  358,  386,  360,  387,  357,

      360,  356,  388,  389,  385,  393,  408,  380,  387,  394,
      410,  422,  388,  386,  420,  394,  414,  393,  420,  413,
      389,  422,  412,  411,  408,  409,  407,  404,  400,  398,
      396,  410,  428,  428,  428,  428,  429,  429,  430,  395,
      430,  430,  431,  431,  431,  431,  432,  392,  432,  432,
      390,  384,  383,  382,  381,  379,  376,  375,  373,  372,
      371,  370,  369,  368,  367,  362,  359,  354,  350,  349,
      346,  345,  338,  333,  331,  330,  329,  328,  326,  325,
      324,  323,  321,  320,  317,  316,  315,  314,  313,  312,
      310,  309,  303,  298,  292,  291,  287,  286,  283,  279,

      272,  260,  259,  258,  256,  255,  254,  253,  251,  250,
      249,  248,  247,  245,  244,  243,  242,  239,  238,  237,
      236,  235,  234,  232,  231,  226,  225,  205,  202,  201,
      199,  190,  188,  181,  179,  175,  162,  156,  147,  146,
      145,  144,  143,  142,  141,  140,  137,  134,  132,  131,
      130,  129,  128,  125,  124,  123,  122,  120,  117,  116,
      113,  109,  107,  104,   96,   90,   86,   84,   83,   74,
       65,   61,   59,   52,   50,   49,   47,   43,   42,   41,
       38,   35,   34,   33,   26,   24,   23,   22,   20,   18,
       11,    9,    8,    7,    6,    3,  427,  427,  427,  427,

      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[66] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "modif.l"
#line 4 "modif.l"
#include<bits/stdc++.h>
using namespace std;
using std::stack; 
stack<int> indents; 
int dedpos = 0; 
int indent = 0;
bool spaceset = false;
int setspace()
{
    spaceset = true;
    if(indent > indents.top()){ 
    indents.push(indent); 
    printf("INDENT\n");
    return 1;
    } 
    int ctr = 0; 
    while(indent < indents.top()){ 
    ctr++; 
    indents.pop(); 
    } 
    if(indents.top() != indent){ 
    printf("Indentation error\n"); 
    return 0;
    } 
    dedpos = ctr; 
    return 0;
}
enum yytokentype 
{ 
NEWLINE = 258, 
ENDMARKER = 259, 
ASYNC = 260, 
NAME = 261, 
DEL = 262, 
PASS = 263, 
BREAK = 264, 
CONTINUE = 265, 
RETURN = 266, 
RAISE = 267, 
FROM = 268, 
IMPORT = 269, 
AS = 270, 
GLOBAL = 271, 
NONLOCAL = 272, 
ASSERT = 273, 
IF = 274, 
ELIF = 275, 
ELSE = 276, 
FOR = 277, 
IN = 278, 
WHILE = 279, 
TRY = 280, 
FINALLY = 281, 
WITH = 282, 
EXCEPT = 283, 
LAMBDA = 284, 
NOT = 285, 
OR = 286, 
AND = 287, 
AWAIT = 288, 
IS = 289, 
INDENT = 290, 
DEDENT = 291, 
YIELD = 292, 
TRUE = 293, 
NUMBER = 294, 
STRING = 295, 
FALSE = 296, 
NONE = 297, 
CLASS = 298, 
DEF = 299, 
ARROWOP = 300, 
POW = 301, 
ADDASSIGN = 302, 
SUBASSIGN = 303, 
MULASSIGN = 304, 
ATASSIGN = 305, 
DIVASSIGN = 306, 
MODASSIGN = 307, 
ANDASSIGN = 308, 
ORASSIGN = 309, 
XORASSIGN = 310, 
LSASSIGN = 311, 
RSASSIGN = 312, 
POWASSIGN = 313, 
IDIVASSIGN = 314, 
ELLIPSIS = 315, 
EQUAL = 316, 
GEQ = 317, 
LEQ = 318, 
LTORGT = 319, 
NEQ = 320, 
LEFTSHIFT = 321, 
RIGHTSHIFT = 322, 
IDIV = 323 
}; 
#line 922 "modif.cpp"
#line 923 "modif.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 168 "modif.l"

#line 170 "modif.l"
    { 
        cerr << "entered " << yylineno << endl;
        if(dedpos > 0){ 
            --dedpos; 
            printf("DEDENT\n");
            return DEDENT;
        } 
    } 
#line 1154 "modif.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 428 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 897 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 178 "modif.l"
{printf("empty\n");/* Ignore blank lines.*/} 
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 181 "modif.l"
{printf("ASYNC\n"); return ASYNC;} 
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 182 "modif.l"
{printf("DEL\n");return DEL;} 
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 183 "modif.l"
{cerr << "there " << yylineno << '\n';if(!spaceset){ cerr << "enter\n"; setspace(); for(int i = yyleng - 1; i >= 0; i--) unput(yytext[i]); return -1;};printf("PASS\n");return PASS;} 
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 184 "modif.l"
{printf("BREAK\n");return BREAK;} 
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 185 "modif.l"
{printf("CONTINUE\n");} 
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 186 "modif.l"
{printf("RETURN\n");} 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 187 "modif.l"
{printf("RAISE\n");} 
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 188 "modif.l"
{printf("FROM\n");} 
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 189 "modif.l"
{printf("IMPORT\n");} 
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 190 "modif.l"
{printf("AS\n");} 
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 191 "modif.l"
{printf("GLOBAL\n");} 
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 192 "modif.l"
{printf("NONLOCAL\n");} 
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 193 "modif.l"
{printf("ASSERT\n");} 
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 194 "modif.l"
{cerr << "here " << yylineno << '\n';if(!spaceset){setspace(); for(int i = yyleng - 1; i >= 0; i--) unput(yytext[i]); return -1;}; printf("IF\n"); return IF;} 
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 195 "modif.l"
{printf("ELIF\n");} 
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 196 "modif.l"
{printf("ELSE\n"); return ELSE;} 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 197 "modif.l"
{printf("FOR\n");} 
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 198 "modif.l"
{printf("IN\n");} 
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 199 "modif.l"
{printf("WHILE\n");} 
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 200 "modif.l"
{printf("TRY\n");} 
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 201 "modif.l"
{printf("FINALLY\n");} 
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 202 "modif.l"
{printf("WITH\n");} 
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 203 "modif.l"
{printf("EXCEPT\n");} 
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 204 "modif.l"
{printf("LAMBDA\n");} 
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 205 "modif.l"
{printf("NOT\n");} 
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 206 "modif.l"
{printf("OR\n");} 
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 207 "modif.l"
{printf("AND\n");} 
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 208 "modif.l"
{printf("AWAIT\n");} 
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 209 "modif.l"
{printf("IS\n");} 
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 210 "modif.l"
{printf("YIELD\n");} 
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 211 "modif.l"
{printf("STRING\n");} 
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 212 "modif.l"
{printf("FALSE\n");} 
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 213 "modif.l"
{printf("NONE\n");} 
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 214 "modif.l"
{printf("CLASS\n");} 
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 215 "modif.l"
{printf("DEF\n");} 
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 217 "modif.l"
{
    indent = 0;printf("newline\n");
    spaceset = false;
    return NEWLINE;} 
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 221 "modif.l"
{printf("comment\n");} 
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 222 "modif.l"
{printf("addassign\n"); ;} 
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 223 "modif.l"
{printf("subassign\n"); ;} 
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 224 "modif.l"
{printf("mulassign\n"); ;} 
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 225 "modif.l"
{printf("divassign\n"); ;} 
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 226 "modif.l"
{printf("idivassign"); ;} 
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 227 "modif.l"
{printf("modassign\n"); ;} 
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 228 "modif.l"
{printf("atassign\n"); ;} 
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 229 "modif.l"
{printf("andassign\n"); ;} 
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 230 "modif.l"
{printf("orassign\n"); ;} 
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 231 "modif.l"
{printf("xorassign\n"); ;} 
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 232 "modif.l"
{printf("lsassign\n"); ;} 
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 233 "modif.l"
{printf("rsassign\n"); ;} 
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 234 "modif.l"
{printf("powassign\n"); ;} 
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 235 "modif.l"
{printf("arrowop\n"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 237 "modif.l"
{printf("pow\n");} 
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 238 "modif.l"
{printf("idiv\n");} 
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 239 "modif.l"
{printf("leftshift\n");} 
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 240 "modif.l"
{printf("rightshift\n");} 
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 241 "modif.l"
{printf("leq\n");} 
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 242 "modif.l"
{printf("geq\n");} 
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 243 "modif.l"
{printf("equal\n"); return EQUAL;} 
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 244 "modif.l"
{printf("neq\n");} 
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 245 "modif.l"
{printf("number\n"); return NUMBER;} 
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 246 "modif.l"
{if(!spaceset){setspace(); for(int i = yyleng - 1; i >= 0; i--) unput(yytext[i]); return -1;}; printf("NAME\n"); return NAME;} 
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 247 "modif.l"
{if(!spaceset) setspace(); printf("Character %c\n", yytext[0]); return yytext[0];}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 248 "modif.l"
{return 0;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 249 "modif.l"
{ 
    printf("enter\n");
    fflush(stdout);
int pos = yyleng - 1; 
while(pos >= 1 and yytext[pos] != ' '){ 
unput(yytext[pos]); 
--pos; 
} 
if(yytext[pos] == ' ') pos++;
indent = pos;
printf("here %d\n", pos);
if(setspace()) return INDENT;
} 
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 262 "modif.l"
ECHO;
	YY_BREAK
#line 1569 "modif.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 428 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 428 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 427);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 262 "modif.l"


int main(int argc, char * argv[]) 
{ 
indents.push(0); 
if(argc > 1){ 
FILE *in = fopen(argv[1], "r"); 
yyin = in; 
} 
else yyin = stdin; 
while(yylex()){
    printf("Done token\n\n");
    fflush(stdout);
}

} 

